use super::types::GameStateEvent;

pub fn get_scenario_default(scenario_name: &str) -> Result<GameStateEvent, String> {
    match scenario_name.to_uppercase().as_str() {
        "SCENARIO_A_DRAFT" | "CHAMP_SELECT" | "CHAMP_SELECT_RENEKTON_VS_AATROX" => Ok(GameStateEvent {
            phase: "CHAMP_SELECT".to_string(),
            connected: true,
            game_time_seconds: 0,
            my_champion: Some("Renekton".to_string()),
            opponent_champion: Some("Aatrox".to_string()),
            opponent_confidence: 85,
            potential_opponents: vec![
                "Aatrox".to_string(),
                "Lee Sin".to_string(),
                "Ahri".to_string(),
                "Kai'Sa".to_string(),
                "Nautilus".to_string(),
            ],
            match_id: Some("draft_sim_001".to_string()),
            match_result: None,
            is_manual_override: false,
            kda: None,
            items_built: None,
            summoners_used: None,
            runes_used: None,
            cs: None,
        }),

        "SCENARIO_B_IN_GAME" | "IN_GAME" | "IN_GAME_VS_DARIUS" => Ok(GameStateEvent {
            phase: "IN_GAME".to_string(),
            connected: true,
            game_time_seconds: 215,
            my_champion: Some("Renekton".to_string()),
            opponent_champion: Some("Darius".to_string()),
            opponent_confidence: 100,
            potential_opponents: vec!["Darius".to_string()],
            match_id: Some("live_sim_darius_002".to_string()),
            match_result: None,
            is_manual_override: false,
            kda: Some("1/0/0".to_string()),
            items_built: Some("Espada de Doran, Poção de Vida".to_string()),
            summoners_used: Some("Flash, Incendiar".to_string()),
            runes_used: Some("Pressione o Ataque".to_string()),
            cs: Some(34),
        }),

        "SCENARIO_C_LANE_SWAP" | "IN_GAME_SWAP" | "LANE_SWAP" => Ok(GameStateEvent {
            phase: "IN_GAME".to_string(),
            connected: true,
            game_time_seconds: 180,
            my_champion: Some("Renekton".to_string()),
            opponent_champion: Some("Yasuo".to_string()),
            opponent_confidence: 70,
            potential_opponents: vec!["Yasuo".to_string(), "Yone".to_string()],
            match_id: Some("swap_sim_003".to_string()),
            match_result: None,
            is_manual_override: false,
            kda: Some("0/0/0".to_string()),
            items_built: Some("Escudo de Doran, Poção de Vida".to_string()),
            summoners_used: Some("Flash, Incendiar".to_string()),
            runes_used: Some("Conquistador".to_string()),
            cs: Some(22),
        }),

        "SCENARIO_D_POST_GAME_WIN" | "POST_GAME" | "POST_GAME_VICTORY" => Ok(GameStateEvent {
            phase: "POST_GAME".to_string(),
            connected: true,
            game_time_seconds: 1720,
            my_champion: Some("Renekton".to_string()),
            opponent_champion: Some("Aatrox".to_string()),
            opponent_confidence: 100,
            potential_opponents: Vec::new(),
            match_id: Some("post_game_win_004".to_string()),
            match_result: Some("WIN".to_string()),
            is_manual_override: false,
            kda: Some("7/2/5".to_string()),
            items_built: Some("Eclipse, Céu Dividido, Passos de Mercúrio, Hidra Titânica".to_string()),
            summoners_used: Some("Flash, Incendiar".to_string()),
            runes_used: Some("Pressione o Ataque".to_string()),
            cs: Some(198),
        }),

        "SCENARIO_E_DISCONNECTED" | "DISCONNECTED" => Ok(GameStateEvent {
            phase: "DISCONNECTED".to_string(),
            connected: false,
            game_time_seconds: 0,
            my_champion: None,
            opponent_champion: None,
            opponent_confidence: 0,
            potential_opponents: Vec::new(),
            match_id: None,
            match_result: None,
            is_manual_override: false,
            kda: None,
            items_built: None,
            summoners_used: None,
            runes_used: None,
            cs: None,
        }),

        "LOBBY" => Ok(GameStateEvent {
            phase: "LOBBY".to_string(),
            connected: true,
            game_time_seconds: 0,
            my_champion: None,
            opponent_champion: None,
            opponent_confidence: 0,
            potential_opponents: Vec::new(),
            match_id: None,
            match_result: None,
            is_manual_override: false,
            kda: None,
            items_built: None,
            summoners_used: None,
            runes_used: None,
            cs: None,
        }),

        _ => Err(format!(
            "Unknown simulation scenario: \"{}\". Available: SCENARIO_A_DRAFT, SCENARIO_B_IN_GAME, SCENARIO_C_LANE_SWAP, SCENARIO_D_POST_GAME_WIN, SCENARIO_E_DISCONNECTED",
            scenario_name
        )),
    }
}
